### PR TITLE
Add Ansible 5.4.0-3

### PR DESCRIPTION
**Pull request by bdunne**
Imported from: https://koji.fedoraproject.org/koji/buildinfo?buildID=2008279

Alternative to #346, particularly for backport reasons.

### CODE REVIEW

**Comment by Fryguy** [comment]
@bdunne A conflict occurred during the backport of this pull request to `oparin`.

If this pull request is based on another pull request that has not been marked for backport, add the appropriate labels to the other pull request. Otherwise, please create a new pull request direct to the `oparin` branch in order to resolve this.

Conflict details:

```diff
* Unmerged path lib/manageiq/rpm_build/extra_package.rb
```

**Comment by Fryguy** [comment]
Temporarily moving back to oparin/yes? because I'm not sure if this should be backported or needs to be done differently for oparin.  @bdunne let me know.

**Comment by bdunne** [comment]
Probably needs https://github.com/ManageIQ/manageiq-rpm_build/pull/338 backported first

**Comment by Fryguy** [comment]
Backported to `oparin` in commit 3d28e62a2c524f9505134decc91931805252d178.

```text
commit 3d28e62a2c524f9505134decc91931805252d178
Author: Jason Frey <fryguy9@gmail.com>
Date:   Thu Dec 1 16:53:02 2022 -0500

    Merge pull request #347 from bdunne/ansible_5
    
    Add Ansible 5.4.0-3
    
    (cherry picked from commit d95fd2caee24e77c8765a3eaa909309b8d425002)
```

**Comment by Fryguy** [comment]
@bdunne A conflict occurred during the backport of this pull request to `najdorf`.

If this pull request is based on another pull request that has not been marked for backport, add the appropriate labels to the other pull request. Otherwise, please create a new pull request direct to the `najdorf` branch in order to resolve this.

Conflict details:

```diff
diff --cc config/options.yml
index 9188c4e,eb57ef2..0000000
--- a/config/options.yml
+++ b/config/options.yml
@@@ -29,19 -30,22 +29,27 @@@ rpm_repository
      bucket: rpm-manageiq-org
      endpoint: nyc3.digitaloceanspaces.com
    :arches:
 -    - "src"
 -    - "noarch"
 -    - "ppc64le"
 -    - "s390x"
 -    - "x86_64"
 +  - src
 +  - noarch
 +  - ppc64le
 +  - s390x
 +  - x86_64
    :content:
 -    :16-petrosian:
 +    :14-najdorf:
        :targets:
 -        - el8
 -        - el9
 +      - el8
        :rpms:
++<<<<<<< HEAD
 +        :kafka: !ruby/regexp /.+-2\.3.+/
 +        :manageiq: !ruby/regexp /.+-14\.\d\.\d-(alpha|beta|rc)?\d(\.\d)?\.el.+/
 +        :manageiq-release: !ruby/regexp /.+-14\.0.+/
++=======
+         :ansible: !ruby/regexp /.+-5\.4.+/
+         :kafka: !ruby/regexp /.+-3\.3.+/
+         :manageiq: !ruby/regexp /.+-16\.\d\.\d-(alpha|beta|rc)?\d(\.\d)?\.el.+/
+         :manageiq-release: !ruby/regexp /.+-16\.0.+/
+         :postgresql: !ruby/regexp /.+-10\.21.+/
++>>>>>>> d95fd2c (Merge pull request #347 from bdunne/ansible_5)
          :python-bambou: !ruby/regexp /.+-3\.1\.1.+/
          :python-pylxca: !ruby/regexp /.+-2\.1\.1.+/
          :python-unittest2: !ruby/regexp /.+-1\.1\.0.+/
* Unmerged path lib/manageiq/rpm_build/extra_package.rb
```

**Comment by Fryguy** [comment]
Backported to morphy via https://github.com/ManageIQ/manageiq-rpm_build/pull/397

**Pull request merged**
