### PR TITLE
Prefer using npm.manageiq.org as a proxy cache for yarn

### PR DESCRIPTION
**Pull request by bdunne**
This should reduce throttling and timeout issues during builds

Sample error:
```
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/core-js/-/core-js-2.6.12.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/root/BUILD/manageiq-gemset-14.0.0/bundler/gems/manageiq-providers-nsxt-d0c7629b7b3f/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...

== yarn failed in /root/BUILD/manageiq-gemset-14.0.0/bundler/gems/manageiq-providers-nsxt-d0c7629b7b3f ==
```

### CODE REVIEW

**Comment by bdunne** [comment]
@Fryguy Let me know what you think.  I can keep the config override on the build machine, but since there's nothing secret I figured we could put it in the default config instead.

**Comment by Fryguy** [comment]
I'm fine with it being in the default config, because that config can be overridden with the OPTIONS

**Comment by Fryguy** [comment]
@bdunne A conflict occurred during the backport of this pull request to `morphy`.

If this pull request is based on another pull request that has not been marked for backport, add the appropriate labels to the other pull request. Otherwise, please create a new pull request direct to the `morphy` branch in order to resolve this.

Conflict details:

```diff
diff --cc config/options.yml
index 4150678,e55c230..0000000
--- a/config/options.yml
+++ b/config/options.yml
@@@ -14,15 -14,15 +14,20 @@@ repos
  version:
  release:
  rpm:
 -  version:         14.0.0
 -  release:         0
 +  version: 13.0.0
 +  release: 0
    repo_name:
 -  org_name:        manageiq
 +  org_name: manageiq
    product_summary: ManageIQ Management Engine
 -  product_url:     https://github.com/ManageIQ/manageiq
 +  product_url: https://github.com/ManageIQ/manageiq
    changelog:
++<<<<<<< HEAD
 +bundler_version: 2.1.4
 +npm_registry:
++=======
+ bundler_version:   2.1.4
+ npm_registry:      https://npm.manageiq.org
++>>>>>>> 7d75d98... Merge pull request #204 from bdunne/add_npm_proxy
  rpm_repository:
    digitalocean_access_token:
    s3_api:
```

**Comment by Fryguy** [comment]
@bdunne I can manually backport this one.

**Comment by Fryguy** [comment]
`morphy` backport details:

```
commit 4832c7d58fb6c94d89905a80bd3726527db393e3 (HEAD -> morphy, upstream/morphy)
Author: Jason Frey <fryguy9@gmail.com>
Date:   Wed Sep 29 14:27:31 2021 -0400

    Merge pull request #204 from bdunne/add_npm_proxy

    Prefer using npm.manageiq.org as a proxy cache for yarn

    (cherry picked from commit 7d75d98facc845b40a607e7321c4870d1a70aec4)
```

**Pull request merged**
