### PR TITLE
Remove ui-classic extra files not needed for production

### PR DESCRIPTION
**Pull request by simaishi**
cc @himdel

### CODE REVIEW

**Review by Fryguy — APPROVED** [review]
LGTM, just want to make sure @himdel approves as well.

**Comment by Fryguy** [comment]
cc @gtanzillo

**Comment by himdel** [comment]
LGTM, `spec/javascripts` is already covered by `gems/*/spec` :+1:

**Comment by simaishi** [comment]
Kasparov backport details:

```
$ git log -1
commit bf3762b7c00334fb5cf0d0fd2a36bda616fe0ec2
Author: Jason Frey <fryguy9@gmail.com>
Date:   Mon Dec 7 11:13:34 2020 -0500

    Merge pull request #124 from simaishi/remove_extra_ui_files

    Remove ui-classic extra files not needed for production

    (cherry picked from commit 172aaf3da0abbfe3413719a8718ebf316fae85c1)
```

**Pull request merged**
