### PR TITLE
Add webpack manifest for the service ui

### PR DESCRIPTION
**Pull request by Fryguy**
@simaishi Please review.

Depends on https://github.com/ManageIQ/manageiq-ui-service/pull/1671

### CODE REVIEW

**Comment by Fryguy** [comment]
cc @himdel @bhadrim

**Comment by Fryguy** [comment]
@simaishi The dependent PR is merged...can you review?

**Comment by simaishi** [comment]
LGTM

**Comment by simaishi** [comment]
@Fryguy Do we want to remove npm_manifest?

**Comment by Fryguy** [comment]
I'm still debating, but if we do we can do that in a seasoned separate PR

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit fb38f2f90aabd0f466b1ccb23d13b3be04a30250
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Mon Sep 14 09:51:37 2020 -0400

    Merge pull request #89 from Fryguy/service_ui_manifest

    Add webpack manifest for the service ui

    (cherry picked from commit 65086cba6e46acb4da62744dfc8f5691e3300552)
```

**Pull request merged**
