### PR TITLE
Bump ipaddress python package

### PR DESCRIPTION
**Pull request by Fryguy**
@agrare Please review.

### CODE REVIEW

**Comment by agrare** [comment]
This is for the error:
`/var/lib/manageiq/venv/lib/python3.8/site-packages/ipaddress.py:1106: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?`

**Review by agrare — APPROVED** [review]

**Comment by Fryguy** [comment]
Backported to `petrosian` in commit 436b95d9c5fa4a32f52c932dc4b2958e41ac8a90.

```text
commit 436b95d9c5fa4a32f52c932dc4b2958e41ac8a90
Author: Adam Grare <adam@grare.com>
Date:   Mon Jul 24 09:37:14 2023 -0400

    Merge pull request #403 from Fryguy/bump_ipaddress
    
    Bump ipaddress python package
    
    (cherry picked from commit b39078998ec68f0adcb1cb07347cba41a17ff3a2)
```

**Comment by Fryguy** [comment]
@Fryguy A conflict occurred during the backport of this pull request to `morphy`.

If this pull request is based on another pull request that has not been marked for backport, add the appropriate labels to the other pull request. Otherwise, please create a new pull request direct to the `morphy` branch in order to resolve this.

Conflict details:

```diff
* Unmerged path config/requirements.txt
```

**Comment by Fryguy** [comment]
Backported to morphy via https://github.com/ManageIQ/manageiq-appliance-build/pull/553

**Pull request merged**
