### PR TITLE
Not really sure why this is here, we specify ~>3.0

### PR DESCRIPTION
**Pull request by bdunne**
https://github.com/ManageIQ/manageiq/blob/a475afa6e8e834e7332b612924fc6f47405f8454/Gemfile#L84

### CODE REVIEW

**Comment by kbrock** [comment]
When you are building rpms, there are 2 different `Gemfile`s in play. right?
Not sure if this is using the `Gemfile` that you are referencing.

Having said that, I do think that dropping the version is a good idea.

Have you had a chance to build rpms with this change?

**Comment by bdunne** [comment]
> When you are building rpms, there are 2 different `Gemfile`s in play. right? Not sure if this is using the `Gemfile` that you are referencing.
> 
> Having said that, I do think that dropping the version is a good idea.
> 
> Have you had a chance to build rpms with this change?

I haven't built rpms with this change yet, it's on my TODO list.

**Comment by Fryguy** [comment]
> When you are building rpms, there are 2 different Gemfiles in play. right?

Which 2 are you referring to?  I thought there is on the one in core?

**Comment by bdunne** [comment]
Images built and installed on an appliance successfully.  I can log in ot the UI, is there anything else that I need to test?

**Comment by kbrock** [comment]
> > When you are building rpms, there are 2 different Gemfiles in play. right?
> 
> Which 2 are you referring to? I thought there is on the one in core?

There is a Gemfile for the local scripts, and a Gemfile inside the docker conatainer from miq core. For a while, they had different dependencies and were even running a different version of ruby/bundler

**Pull request merged**
