### PR TITLE
Add dependency on the kafka package

### PR DESCRIPTION
**Pull request by bdunne**

### CODE REVIEW

**Comment by bdunne** [comment]
Marking as WIP until the appliance console work is ready to go.

**Comment by bdunne** [comment]
Un-WIP since the appliance console work is close to done.  kasparov/no since this is targeted for lasker.

**Comment by simaishi** [comment]
@bdunne I see only x86_64 rpm built, so this will break pcc64le. I think we need to either build ppc64le rpm or put `%ifarch x86_64` around it.

**Comment by bdunne** [comment]
@simaishi @Fryguy I added the Kafka PPC RPM, so we're ready to merge this.

**Comment by Fryguy** [comment]
Backported to `morphy` in commit abd031d9e3f730ebc7dee58b0eff0c1e30d4c6c9.

```text
commit abd031d9e3f730ebc7dee58b0eff0c1e30d4c6c9
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Mar 30 09:41:26 2021 -0400

    Merge pull request #91 from bdunne/add_kafka
    
    Add dependency on the kafka package
    
    (cherry picked from commit 8c799ac75bb743d1192fa54d8fd3cfba5fcfb472)
```

**Pull request merged**
