### PR TITLE
Remove sqlite

### PR DESCRIPTION
**Pull request by Fryguy**
Depends on https://github.com/ManageIQ/manageiq/pull/21052

### CODE REVIEW

**Review by chessbyte — APPROVED** [review]

**Comment by Fryguy** [comment]
I'm marking this particular one as WIP, because I'm not 100% sure it will work.  @bdunne Can you help me verify if this will work?

**Comment by jrafanie** [comment]
> I'm marking this particular one as WIP, because I'm not 100% sure it will work. @bdunne Can you help me verify if this will work?


Here's what the rpm metadata tells us about what packages depend on it:

```
[root@76a19447a085 /]# dnf repoquery --whatrequires sqlite
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

Last metadata expiration check: 0:00:17 ago on Wed 24 Mar 2021 04:54:36 PM UTC.
exim-greylist-0:4.94-1.el8.x86_64
libchewing-0:0.5.1-17.el8.x86_64
mono-data-sqlite-0:6.8.0-4.el8.x86_64
ovirt-engine-tools-backup-0:4.4.3.10-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.3.11-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.3.12-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.3.5-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.3.6-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.3.7-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.3.8-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.3.9-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.4-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.4.1-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.4.2-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.4.3-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.4.4-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.4.5-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.4.7-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.5.10-1.el8.noarch
ovirt-engine-tools-backup-0:4.4.5.11-1.el8.noarch
retrace-server-0:1.22.4-1.el8.noarch
sqlite-devel-0:3.26.0-11.el8.i686
sqlite-devel-0:3.26.0-11.el8.x86_64
```

```
[root@76a19447a085 /]# dnf repoquery --whatrequires sqlite-devel
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

Last metadata expiration check: 0:00:54 ago on Wed 24 Mar 2021 04:54:36 PM UTC.
createrepo_c-devel-0:0.15.11-2.el8.i686
createrepo_c-devel-0:0.15.11-2.el8.x86_64
evolution-data-server-devel-0:3.28.5-14.el8.i686
evolution-data-server-devel-0:3.28.5-14.el8.x86_64
libsq3-devel-0:20071018-26.el8.x86_64
libsqlite3x-devel-0:20071018-26.el8.x86_64
proftpd-devel-0:1.3.6e-2.el8.x86_64
sleuthkit-devel-0:4.9.0-1.el8.x86_64
soci-sqlite3-devel-0:4.0.0-2.el8.x86_64
subversion-devel-0:1.10.2-4.module_el8.3.0+703+ba2f61b7.x86_64
```

**Comment by Fryguy** [comment]
@jrafanie - I upWIP'd this - if you're good can you merge?

**Comment by jrafanie** [comment]
Maybe I'll do a build with this change and a local change to drop nodejs.

**Review by jrafanie — APPROVED** [review]

**Comment by chessbyte** [comment]
Less is more!

**Comment by bdunne** [comment]
@Fryguy do you want to bring this back to morphy?

**Comment by Fryguy** [comment]
That means the radar deletion should come back too

**Comment by kbrock** [comment]
You tend to need the `-devel` rpms when you are installing the gems used by active record.
Since we are not supporting sqlite as our database, and therefore not installing the sqlite gem, then we do not need this rpm

**Comment by Fryguy** [comment]
Backported to `morphy` in commit 4b1884f59ae0dfe8d7c3d969235695186ef282b8.

```text
commit 4b1884f59ae0dfe8d7c3d969235695186ef282b8
Author: Joe Rafaniello <jrafanie@users.noreply.github.com>
Date:   Fri Mar 26 15:06:02 2021 -0400

    Merge pull request #136 from Fryguy/drop_sqlite
    
    Remove sqlite
    
    (cherry picked from commit 4baf1eb97ee22e222d6c74811ed2a463c6397930)
```

**Pull request merged**
