### PR TITLE
Upgrade to kafka v3.7.0 on openjdk-11

### PR DESCRIPTION
**Pull request by bdunne**
No reason to bring gradle ourselves, the build step downloads it anyway.

Download: https://rpm.manageiq.org/builds/kafka/kafka-3.7.0-1.el9.x86_64.rpm

### CODE REVIEW

**Review by Fryguy — APPROVED** [review]
Would also like @nasark to review

**Review by nasark — APPROVED** [review]
LGTM, I tested the rpm on the latest appliance build and can see successful health checks and handling of events

**Comment by Fryguy** [comment]
@bdunne A conflict occurred during the backport of this pull request to `radjabov`.

If this pull request is based on another pull request that has not been marked for backport, add the appropriate labels to the other pull request. Otherwise, please create a new pull request direct to the `radjabov` branch in order to resolve this.

Conflict details:

```diff
diff --cc config/options.yml
index df0150a,0a0b795..0000000
--- a/config/options.yml
+++ b/config/options.yml
@@@ -40,9 -40,9 +40,15 @@@ rpm_repository
        :targets:
        - el9
        :rpms:
++<<<<<<< HEAD
 +        :kafka: !ruby/regexp /.+-3\.3.+/
 +        :manageiq: !ruby/regexp /.+-18\.\d\.\d-(alpha|beta|rc)?\d(\.\d)?\.el.+/
 +        :manageiq-release: !ruby/regexp /.+-18\.0.+/
++=======
+         :kafka: !ruby/regexp /.+-3\.7.+/
+         :manageiq: !ruby/regexp /.+-19\.\d\.\d-(alpha|beta|rc)?\d(\.\d)?\.el.+/
+         :manageiq-release: !ruby/regexp /.+-19\.0.+/
++>>>>>>> 6fd373b (Merge pull request #447 from bdunne/kafka_upgrade)
          :python-bambou: !ruby/regexp /.+-3\.1\.1.+/
          :python-pylxca: !ruby/regexp /.+-2\.1\.1.+/
          :python-unittest2: !ruby/regexp /.+-1\.1\.0.+/
```

**Comment by Fryguy** [comment]
Manually backported to `radjabov` via e9526dabd63901a0335a41aaf4c4246613de1d7f

```
commit e9526dabd63901a0335a41aaf4c4246613de1d7f (HEAD -> radjabov, origin/radjabov)
Author: Jason Frey <fryguy9@gmail.com>
Date:   Wed Mar 6 16:13:39 2024 -0500

    Merge pull request #447 from bdunne/kafka_upgrade

    Upgrade to kafka v3.7.0 on openjdk-11

    (cherry picked from commit 6fd373b4f1a64a6be1f06ccacddc6f1cf9bd90ef)
```

**Pull request merged**
