### PR TITLE
Add opentofu-runner service

### PR DESCRIPTION
**Pull request by agrare**
Depends on:
- [ ] https://github.com/ManageIQ/manageiq-providers-embedded_terraform/pull/2

### CODE REVIEW

**Comment by Fryguy** [comment]
Can you add this type of thing to the pluggability checklist as well?

**Comment by agrare** [comment]
I can add it but I'm not sure how pluggable the RPM build is or can be, not aware of any other aspect of it that we have overridden in plugins @bdunne ?

**Comment by Fryguy** [comment]
We have systemd units pluggable but it's pluggable generically by name (i.e. manageiq-providers-*) on the rpm side... Not sure how we can do it any differently

**Comment by agrare** [comment]
Right the opentofu-runner.service content is already defined in the provider repo, one thing that comes to mind is if we don't care about splitting up "core-services" and "gemset-services" we could just take `%{_prefix}/lib/systemd/system/*.{service,target}`

**Comment by Fryguy** [comment]
Yeah I'm not sure why we have them split other than the rpms themselves are split that way

**Pull request merged**
